apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
  namespace: prod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: apigateway-service
